spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liuhang12


mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.mybatis.entity

server:
  port: 8081

